"""The migrations themselves, run against the test database."""

from __future__ import annotations

from alembic import command
from alembic.script import ScriptDirectory

from tests.support.database import alembic_config, migrate_fresh_schema, query


def test_single_head() -> None:
    script = ScriptDirectory.from_config(alembic_config())

    assert len(script.get_heads()) == 1


def test_models_match_migrations() -> None:
    # Fails with AutogenerateDiffsDetected if a model changed without a migration.
    command.check(alembic_config())


def test_downgrade_removes_everything_and_upgrade_restores_it() -> None:
    config = alembic_config()

    try:
        command.downgrade(config, "base")

        tables = query("SELECT tablename FROM pg_tables WHERE schemaname = 'public'")
        types = query(
            "SELECT typname FROM pg_type JOIN pg_namespace n ON n.oid = typnamespace"
            " WHERE nspname = 'public' AND typtype = 'e'"
        )
        assert tables == [("alembic_version",)]
        assert types == []

        command.upgrade(config, "head")
        command.check(config)
    finally:
        # The other tests share this database: leave it migrated even if this failed.
        migrate_fresh_schema()
