"""The migrations: one line of history that matches the models."""

from __future__ import annotations

from alembic import command
from alembic.script import ScriptDirectory

from tests.support.database import alembic_config


def test_single_head() -> None:
    script = ScriptDirectory.from_config(alembic_config())

    assert len(script.get_heads()) == 1


def test_models_match_migrations() -> None:
    # Fails with AutogenerateDiffsDetected if a model changed without a migration.
    command.check(alembic_config())
